check for pipeline fail (#56)
* added another step with outputs defined

* more debug statements to know what's happening

* check for hard coded value

* added missing path to access output var

* check for versioning with two steps

* corrected the path for output var

* added caching to deploy script

* check for pipline fail

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -41,6 +41,13 @@ jobs:
         name: versioning type
         run: echo "versiontype=${{ env.VERSION_TYPE }}" >> $GITHUB_OUTPUT
 
+      - name: check for UNDEFINED version
+        if: ${{ env.VERSION_TYPE == 'undefined' }}
+        run: |
+          echo "Failing further steps since there wasn't a build version which was determined."
+          echo "If the intention was to bump the pjg version then please make sure to tag (ex: [PATCH]) your commit message as per instructions from 'commit instructions' under readme"  
+          exit 1 # fails the job
+
   bump_pkg_version:
     runs-on: ubuntu-latest
     needs: version_type_finder
